baseURL = "http://example.com"
title = "TEVH"
author = "TEVH"
theme = "simple-snipcart-shop"
contentDir = "products"

[params]
  instagram = "tevh_tech"
  header = "探索视觉极限"
  description = "TEVH专注高端显示技术，提供4K/8K超高清、广色域覆盖与超低延迟的专业显示解决方案"
  products_title = "TEVH产品系列"
  reviews_title = "用户见证"
  not_found = "当前分类暂无产品"
  categories = [
    "电竞系列",
    "专业设计",
  ]
  collage = [
    "/images/collage-1.jpg",
    "/images/collage-2.jpg",
    "/images/collage-3.jpg",
    "/images/collage-8.jpg",
    "/images/collage-7.jpg",
    "/images/collage-4.jpg",
    "/images/collage-5.jpg",
    "/images/collage-6.jpg"
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  snipcart_key = ""
  favicon= "/images/favicon.jpg"

[params.tech_specs]
  resolutions = ["4K UHD", "2K QHD", "1080p FHD"]
  refresh_rates = ["240Hz", "144Hz", "75Hz"]
  panel_types = ["IPS", "VA", "TN"]
  response_times = ["1ms", "4ms", "8ms"]  # 新增响应时间参数
  brightness = ["400nits", "600nits"]     # 新增亮度参数
  contrast = ["1000:1", "3000:1"]        # 新增对比度参数
